#!/bin/bash
# # This file is @generated by <https://github.com/liblaf/copier-typescript>.
# DO NOT EDIT!

GIT_ROOT=$(git rev-parse --show-toplevel 2> /dev/null || realpath "../..")

PATH_add "$GIT_ROOT/node_modules/.bin"
